spring.application.name=kalium
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kaliumdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kalium}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kalium}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.config.import=optional:classpath:application-secret.properties

logging.level.root=WARN
logging.level.com.laboQuimica.kalium=DEBUG
logging.level.com.laboQuimica.kalium.service.NotificacionWebSocketService=DEBUG